// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkingDiary;

#nullable disable

namespace WorkingDiary.Migrations
{
    [DbContext(typeof(WorkersDbContext))]
    [Migration("20240322085740_WorkerTasks")]
    partial class WorkerTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkingDiary.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("worker_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("WorkerDepartment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("worker_department");

                    b.Property<string>("WorkerLastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("worker_lastname");

                    b.Property<string>("WorkerLogin")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("worker_login");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("worker_name");

                    b.Property<string>("WorkerPassword")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("worker_password");

                    b.Property<string>("WorkerSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("worker_surname");

                    b.HasKey("WorkerId")
                        .HasName("id_key");

                    b.ToTable("worker", (string)null);
                });

            modelBuilder.Entity("WorkingDiary.WorkerTask", b =>
                {
                    b.Property<DateOnly?>("TaskCreateDate")
                        .HasColumnType("date")
                        .HasColumnName("task_create_date");

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("task_description");

                    b.Property<DateOnly?>("TaskEndDate")
                        .HasColumnType("date")
                        .HasColumnName("task_end_date");

                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("task_id")
                        .HasDefaultValueSql("nextval('tasks_task_id_seq'::regclass)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_name");

                    b.Property<string>("TaskOwnerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_owner_name");

                    b.Property<string>("TaskOwnerSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_owner_surname");

                    b.Property<string>("TaskStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("task_status");

                    b.ToTable("worker_tasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
